const assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm');
const captions=require('../public/partner-captions.js');
class Emitter {constructor(){this.handlers={};}on(name,fn){(this.handlers[name]||(this.handlers[name]=[])).push(fn);}emit(name,value){(this.handlers[name]||[]).slice().forEach(fn=>fn(value));}addEventListener(n,f){this.on(n,f);}removeEventListener(n,f){this.handlers[n]=(this.handlers[n]||[]).filter(x=>x!==f);}dispatchEvent(e){this.emit(e.type,e);}}
let clock=Date.parse('2026-10-04T04:00:00Z'),seq=0;const tasks=new Map();function later(fn,ms){tasks.set(++seq,{fn,at:clock+ms});return seq;}function cancel(id){tasks.delete(id);}function advance(ms){clock+=ms;for(const [id,t] of [...tasks])if(t.at<=clock){tasks.delete(id);t.fn();}}
class Conn extends Emitter{constructor(peer,label){super();this.peer=peer;this.label=label;this.open=true;this.sent=[];}send(p){this.sent.push(p);this.other.emit('data',p);}close(){if(!this.open)return;this.open=false;this.emit('close');if(this.other.open){this.other.open=false;this.other.emit('close');}}}
const network=new Map();class Peer extends Emitter{constructor(id){super();this.id=id;this.open=true;network.set(id,this);this.connections=[];}connect(id,opts){const remote=network.get(id);if(!remote)throw Error('unavailable');const a=new Conn(id,opts.label),b=new Conn(this.id,opts.label);a.other=b;b.other=a;this.connections.push(a);remote.connections.push(b);remote.emit('connection',b);return a;}}
const bookingId='11111111-1111-4111-8111-111111111111',partnerId='partner-auth',learnerId='learner-auth';const common={allowed:true,language:'en',wordHelpTargetLanguage:'en',bookingId,partnerId,learnerId};const pd=new Emitter(),ud=new Emitter(),shown=[];let userTranscript=[];const pc=captions.create({access:{...common,role:'partner',userId:partnerId},document:pd,now:()=>clock,setTimeout:later,clearTimeout:cancel});const uc=captions.create({access:{...common,role:'user',userId:learnerId},document:ud,now:()=>clock,setTimeout:later,clearTimeout:cancel,render:s=>shown.push({...s})});const pp=new Peer('room_host'),up=new Peer('room_user');pc.bindPeer(pp);uc.bindPeer(up);pc.setRemotePeer(up.id);uc.setRemotePeer(pp.id);
// Exercise the real local final path, including recognition-result identity deduplication.
const live=fs.readFileSync('public/room-live.js','utf8');const push=live.slice(live.indexOf('  function pushTranscript'),live.indexOf('  function localTranscriptSpeaker'));const onresult=live.slice(live.indexOf('      recognition.onresult ='),live.indexOf('      recognition.onerror ='));const sttContext={transcriptFinalized:false,transcriptRevision:0,sessionTranscript:[],utteranceSeq:0,window:{sessionTranscript:[],__dayoPreflightActive:false},console:{log(){}},Date,uuid:()=>String(++seq),appendTranscriptRowToViewer(){},backupTranscriptLocal(){},document:pd,CustomEvent:class{constructor(type,options){this.type=type;this.detail=options.detail;}},recognition:{},run:{finals:new Set()},currentRecognitionRun:()=>true,scheduleTranscriptCheckpoint(){},recordSttState(){},scheduleCopilot(){},localTranscriptSpeaker:()=> 'partner'};vm.runInNewContext(push+onresult,sttContext);const results=[];function final(text,isFinal=true,index=results.length){results[index]=Object.assign([{transcript:text}],{isFinal});sttContext.recognition.onresult({resultIndex:index,results});}
// Real wall clock timestamp from pushTranscript is accepted in the controlled clock.
clock=Date.now();final('I like savory food.');assert.equal(shown.at(-1).text,'I like savory food.');assert.equal(sttContext.sessionTranscript.length,1);const firstPacket=pp.connections.at(-1).sent.at(-1);assert.equal(firstPacket.id,sttContext.sessionTranscript[0].id);assert.equal(firstPacket.speaker,'partner');assert.equal(userTranscript.length,0);final('I like savory food.',true,0);assert.equal(sttContext.sessionTranscript.length,1);assert.equal(pp.connections.at(-1).sent.length,1);final('I like savory food.');assert.equal(sttContext.sessionTranscript.length,2,'new final index preserves legitimate repetition');assert.equal(pp.connections.at(-1).sent.length,2);final('interim is not a caption',false);assert.equal(pp.connections.at(-1).sent.length,2);
const stateCount=shown.length;for(const mutation of [{speaker:'learner'},{sender_id:'stranger'},{booking_id:'other'},{recipient_id:'other'},{language:'ko'},{sent_at:clock-9000},{sent_at:clock+5000}])up.connections.at(-1).emit('data',{...firstPacket,id:'bad-'+JSON.stringify(mutation),...mutation});up.connections.at(-1).emit('data',firstPacket);assert.equal(shown.length,stateCount,'reject wrong participant/session, stale and duplicate packets');
pc.setRemotePeer('wrong-peer');final('Do not leak across calls.');assert.equal(shown.at(-1).text,'');pc.setRemotePeer(up.id);advance(2000);uc.toggle();assert.equal(shown.at(-1).text,'');const entry={id:'second',speaker:'partner',text:'This is an English caption.',timestamp:new Date(clock)};pd.dispatchEvent({type:'dayo:transcript',detail:entry});assert.equal(shown.at(-1).text,'');uc.toggle();assert.equal(shown.at(-1).text,entry.text);advance(8001);assert.equal(shown.at(-1).text,'');
// Reconnect clears stale presentation and accepts new finals, without transcript replay.
up.connections.at(-1).close();assert.equal(shown.at(-1).text,'');advance(2000);pd.dispatchEvent({type:'dayo:transcript',detail:{...entry,id:'after-reconnect',timestamp:new Date(clock)}});assert.equal(shown.at(-1).text,entry.text);up.connections.at(-1).emit('data',firstPacket);assert.equal(shown.at(-1).text,entry.text);const nextPeer=new Peer('room_user_2');pc.setRemotePeer(nextPeer.id);uc.bindPeer(nextPeer);uc.setRemotePeer(pp.id);pd.dispatchEvent({type:'dayo:transcript',detail:{...entry,id:'new-peer',timestamp:new Date(clock)}});assert.equal(shown.at(-1).text,entry.text);uc.destroy();pc.destroy();pd.dispatchEvent({type:'dayo:transcript',detail:{...entry,id:'after-end',timestamp:new Date(clock)}});assert.equal(shown.at(-1).available,false);
for(const overrides of [{role:'user',userId:learnerId,language:'ko',wordHelpTargetLanguage:'ko'},{role:'observer',userId:learnerId},{role:'user',userId:learnerId,adminTest:true},{role:'user',userId:'stranger'}]){const p=new Peer('disabled-'+(++seq));const c=captions.create({access:{...common,...overrides}});c.bindPeer(p);c.setRemotePeer(pp.id);assert.equal(p.connections.length,0);c.destroy();}
// A stalled data-channel handshake expires and retries without touching the media peer.
let attempts=0,closed=0; const stalled=new Emitter(); stalled.open=true;
stalled.connect=function(id,opts){attempts++;const conn=new Emitter();conn.peer=id;conn.label=opts.label;conn.open=false;let ended=false;conn.close=()=>{if(ended)return;ended=true;closed++;conn.emit('close');};return conn;};
const waiting=captions.create({access:{...common,role:'user',userId:learnerId},now:()=>clock,setTimeout:later,clearTimeout:cancel});waiting.bindPeer(stalled);waiting.setRemotePeer('slow-host');assert.equal(attempts,1);advance(6001);assert.equal(closed,1);advance(2000);assert.equal(attempts,2);waiting.destroy();assert.equal(closed,2);
// Only the presentation payload is bounded; the original transcript entry is preserved.
const longDoc=new Emitter(),longPartner=new Peer('long-host'),longUser=new Peer('long-user'),longShown=[];
const longSender=captions.create({access:{...common,role:'partner',userId:partnerId},document:longDoc,now:()=>clock,setTimeout:later,clearTimeout:cancel});
const longReceiver=captions.create({access:{...common,role:'user',userId:learnerId},now:()=>clock,setTimeout:later,clearTimeout:cancel,render:s=>longShown.push(s)});
longSender.bindPeer(longPartner);longSender.setRemotePeer(longUser.id);longReceiver.bindPeer(longUser);longReceiver.setRemotePeer(longPartner.id);
const longEntry={id:'long-final',speaker:'partner',text:'English sentence. '.repeat(30),timestamp:new Date(clock)};const originalText=longEntry.text;longDoc.dispatchEvent({type:'dayo:transcript',detail:longEntry});assert.equal(longShown.at(-1).text.length,400);assert.equal(longEntry.text,originalText);longSender.destroy();longReceiver.destroy();
const room=fs.readFileSync('public/room.html','utf8');assert.equal(room,fs.readFileSync('room.html','utf8'));assert.equal(fs.readFileSync('public/partner-captions.js','utf8'),fs.readFileSync('partner-captions.js','utf8'));assert.match(room,/partnerCaptions.setRemotePeer\(call.peer\)/);assert.match(room,/partnerCaptions.setRemotePeer\(''\)/);assert.match(room,/id="partnerCaption" hidden/);assert.match(room,/-webkit-line-clamp: 2/);assert.doesNotMatch(fs.readFileSync('public/partner-captions.js','utf8'),/pushTranscript|saveSessionLog|\.rpc\(|SpeechRecognition|fetch\(/);console.log('Partner captions fixtures passed: real STT final -> existing transcript -> bound peer -> User caption; no duplicate saves, role/session/stale rejection, toggle, expiry, reconnect and teardown.');
