const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),vm=require('node:vm'),cp=require('node:child_process');
const root=path.resolve(__dirname,'..'),read=f=>fs.readFileSync(path.join(root,f),'utf8'),contract=require('../public/partner-report-contract.js');
for(const f of ['room.html','partner-report-contract.js','partner-report.js','partner-report.css'])assert.equal(read('public/'+f),read(f));
assert.equal(contract.treats.length,6);assert.deepEqual(contract.treats.map(t=>t.code),['americano','green_tea','vanilla_latte','cookie','croissant','macaron']);assert.equal(contract.treats[3].meaning,'Curious questions');
for(const id of ['a','b','c','d','e','f','g'])assert(!/[{}]/.test(contract.note(id,{language:'es',topic:'Pasta'},'Seoul Forest cafés')));
assert.match(contract.note('a',{language:'es'}),/in Spanish/);assert.doesNotMatch(contract.note('a',{}),/English|undefined/);assert.equal(contract.note('e',{}),'');assert.equal(contract.note('g',{}),'');assert.match(contract.note('f',{},'Pasta café'),/Pasta café/);
assert.deepEqual(contract.suggestions({}),[]);
assert.deepEqual(contract.suggestions({transcript:[{speaker:'partner',text:'Coffee coffee coffee.'}]}),[]);
assert.deepEqual(contract.suggestions({transcript:[{speaker:'partner',text:'Seoul Forest cafés. Making pasta at home. Busan beach trip.'}]}),['making pasta at home','Seoul Forest cafés','Busan trip']);
assert.deepEqual(contract.suggestions({transcript:[{speaker:'learner',text:'Seoul Forest cafés'}]}),[]);
assert.deepEqual(contract.suggestions({transcript:[{speaker:'partner',text:'thing time day people question conversation user partner language English'}]}),[]);
assert.deepEqual(contract.suggestions({talkCard:{question_en:'What is your favorite coffee?'}}),[]);
assert.deepEqual(contract.suggestions({topic:'Pottery'}),[]);
assert.equal(contract.safeKeyword('mail@example.com'),'');assert.equal(contract.safeKeyword('https://private.invalid'),'');
const url=decodeURIComponent(contract.illustrationUrl('Seoul Forest café',4));assert.match(url,/warm editorial illustration/);assert.match(url,/No text, no typography/);assert.doesNotMatch(url,/transcript|private learner/i);
const room=read('public/room.html');for(const m of room.matchAll(/<script(?:\s[^>]*)?>([\s\S]*?)<\/script>/gi)){if(m[1].trim())new vm.Script(m[1]);}new vm.Script(read('public/partner-report.js'));new vm.Script(read('public/partner-report-contract.js'));
const popup=room.slice(room.indexOf('  <div id="partner-report-popup"'),room.indexOf('<div id="early-exit-modal"'));assert.doesNotMatch(popup,/notesReview|synonyms|nuance|card-sentence-options|spoken_sentence/);assert.match(popup,/pr-note-templates/);assert.match(popup,/View conversation transcript/);
const open=room.slice(room.indexOf('window.openPartnerReportPopup = function'),room.indexOf('function setPartnerReportSubmitStatus'));assert.doesNotMatch(open,/startPartnerSentencePolling|initInstaCardSection/);assert.match(open,/DayOPartnerReport.open/);
const baseline=cp.execFileSync('git',['show','c0f34f8b15598951b25defa1dc989668d87ec360:public/room.html'],{cwd:root,encoding:'utf8'}),normalize=s=>s.replace(/\r/g,'');
function section(s,start,end){return normalize(s.slice(s.indexOf(start),s.indexOf(end,s.indexOf(start))))}
assert.equal(section(room,'function closeInstantQuiz()','/* Partner copilot'),section(baseline,'function closeInstantQuiz()','/* Partner copilot'),'Quiz close/timer behavior unchanged; shared Recap/Letter rendering tested separately');
assert.equal(section(room,'var rewardPromise =','window.submitPartnerReportAndLeave').replace(/^[ \t]*if\(reportSave\.ok&&window\.DayOPartnerIllustration\).*\n/gm,''),section(baseline,'var rewardPromise =','window.submitPartnerReportAndLeave'),'Reward/failure/retry behavior unchanged');
// Preserve the historical Partner/Quiz contract while allowing the independently tested Learner Recap hooks.
const oldFile=f=>normalize(cp.execFileSync('git',['show','c0f34f8b15598951b25defa1dc989668d87ec360:'+f],{cwd:root,encoding:'utf8'}));
for(const f of ['public/room-live.js'])assert.equal(normalize(read(f)),oldFile(f),f+' unchanged');
const currentQuiz=normalize(read('public/memory-game.js')), priorQuiz=oldFile('public/memory-game.js');
for(const [start,end] of [['  function recoverState','  function progress'],['  function progress','  function stopTimer'],['  function renderQuestion','  function showSaveFailure'],['  async function finish','  window.startRecapQuestions']])assert.equal(section(currentQuiz,start,end),section(priorQuiz,start,end),'Quiz question/progress/save algorithms unchanged');
const lifecycle=normalize(read('public/session-lifecycle.js'));
assert.equal(section(lifecycle,'  function buildReviewSnapshot()','  function endCopy'),section(oldFile('public/session-lifecycle.js'),'  function buildReviewSnapshot()','  function endCopy'),'Learner write allowlist and save/retry unchanged');
assert.equal(section(lifecycle,'  function finalizeConversation(reason)','  window.refreshSessionPartnerLetter'),section(oldFile('public/session-lifecycle.js'),'  function finalizeConversation(reason)','  window.getLearnerReviewSnapshot'),'Settlement, safety and media finalization unchanged');
const client=normalize(read('public/supabase-client.js')),oldClient=oldFile('public/supabase-client.js');
assert.equal(section(client,'(function','  function isPlaceholderReport'),section(oldClient,'(function','  function isPlaceholderReport'),'Auth and shared client behavior unchanged');
const inline=s=>Array.from(s.matchAll(/<script(?:\s[^>]*)?>([\s\S]*?)<\/script>/gi)).map(m=>normalize(m[1]).trim()).filter(Boolean);
assert.deepEqual(inline(read('public/mypage.html')),inline(oldFile('public/mypage.html')),'My Page inline behavior unchanged');
console.log('PASS: A–G templates, actual language/optional topic, Treat codes, 0/1/3 keywords, partner-only sources, safe image prompt, syntax/mirrors, protected Quiz/lifecycle/client/My Page behavior unchanged, exact persistence/failure isolation preservation.');
