const assert=require('node:assert/strict'),fs=require('node:fs'),cp=require('node:child_process');
const contract=require('../public/partner-report-contract.js');
const suggest=(rows,extra={})=>contract.suggestions(Object.assign({transcript:rows.map(text=>({speaker:'partner',text}))},extra));
assert.deepEqual(suggest(['Seoul / Forest / café / coffee','Seoul / Forest / café / coffee']),['Seoul Forest cafés']);
assert.deepEqual(suggest(['pasta cook home','pasta cooking home']),['making pasta at home']);
assert.deepEqual(suggest(['thing time day yes no okay really good friend food go place']),[]);
assert.deepEqual(suggest(['Seoul Forest']),['Seoul Forest']);
assert.deepEqual(suggest(['Seoul Forest cafés and coffee']),['Seoul Forest cafés']);
assert.deepEqual(suggest(['Busan travel beach','Busan beach trip']),['Busan trip']);
assert.deepEqual(suggest(['I study at a café']),['studying at a café']);
assert.deepEqual(suggest(['Rainy weather in Seoul']),['rainy weather in Seoul']);
assert.deepEqual(suggest(['K-pop concerts']),['K-pop concerts']);
assert.deepEqual(suggest(['Seoul', 'We read books.', 'Different topic.', 'Forest', 'coffee']),['reading books'],'distant fragments must not invent Seoul Forest cafés');
assert.deepEqual(suggest(['pasta'],{talkCard:{topic:'Cooking pasta at home'}}),['making pasta at home']);
assert.deepEqual(suggest(['I went to Seoul Forest cafés twice.','Busan trip.','Making pasta at home.','Seoul Forest cafés again.']).length,3);
assert.deepEqual(suggest(['Coffee coffee coffee friend forest place food']),[]);
assert.deepEqual(contract.suggestions({transcript:[{speaker:'learner',text:'Seoul Forest cafés'}]}),[]);
assert.equal(contract.illustrationUrl('John Smith at 12 Elm Road'),null);
assert.equal(contract.illustrationUrl('john@example.com'),null);
const image=decodeURIComponent(contract.illustrationUrl('John and I enjoyed Seoul Forest cafés',7));
assert.match(image,/inspired by a cozy café near Seoul Forest/);
assert.doesNotMatch(image,/John|transcript|Elm Road/);
assert.match(image,/No text, no typography, no letters, no speech bubbles/);
assert.match(decodeURIComponent(contract.illustrationUrl('Busan trip',7)),/inspired by a trip to Busan/);
const baseline=cp.execFileSync('git',['show','231efce:public/partner-report-contract.js'],{encoding:'utf8'}).replace(/\r/g,'');
const current=fs.readFileSync('public/partner-report-contract.js','utf8').replace(/\r/g,'');
assert.equal(current.slice(0,current.indexOf(' // Supported topic rules')),baseline.slice(0,baseline.indexOf(' // Conservative noun vocabulary')),'Note/Treat contract unchanged');
const room=fs.readFileSync('public/room.html','utf8').replace(/\r/g,'');
const oldRoom=cp.execFileSync('git',['show','231efce:public/room.html'],{encoding:'utf8'}).replace(/\r/g,'');
function section(s,a,b){return s.slice(s.indexOf(a),s.indexOf(b,s.indexOf(a)));}
assert.equal(section(room,'window.executePartnerPayoutAndExit =','window.handleHeaderExitClick ='),section(oldRoom,'window.executePartnerPayoutAndExit =','window.handleHeaderExitClick ='),'submit/persistence unchanged');
assert.equal(section(room,'<section class="pr-section"><h3>1.','<section class="pr-section"><h3>3.'),section(oldRoom,'<section class="pr-section"><h3>1.','<section class="pr-section"><h3>3.'),'Note/Treat UI unchanged');
assert.equal(fs.readFileSync('public/partner-report.css','utf8').replace(/\r/g,''),cp.execFileSync('git',['show','231efce:public/partner-report.css'],{encoding:'utf8'}).replace(/\r/g,''),'CSS unchanged');
console.log('PASS: grouped nearby fragments, preserved named entities, 0–3 grounded phrases, shared context, generic/learner exclusions, private prompt boundary, Note/Treat/submission/CSS unchanged.');
